open Ints

include Instruction_types

let fetch memory ~pc =
  let open Registers in
  let op = Memory.read_byte memory pc |> Uint8.to_int in
  let next_byte () = Memory.read_byte memory Uint16.(succ pc) in
  let next_word () = Memory.read_word memory Uint16.(succ pc) in
  match op with
  | 0x00 -> NOP
  | 0x01 -> LD (RR_direct BC, Immediate16 (next_word ()))
  | 0x02 -> LD (RR_indirect BC, R_direct A)
  | 0x03 -> INC (RR_direct BC)
  | 0x04 -> INC (R_direct B)
  | 0x05 -> DEC (R_direct B)
  | 0x06 -> LD (R_direct B, Immediate8 (next_byte ()))
  | 0x07 -> RLCA
  | 0x08 -> LD (Direct (next_word ()), SP)
  | 0x09 -> ADD (To_HL (RR_direct BC))
  | 0x0A -> LD (R_direct A, RR_indirect BC)
  | 0x0B -> DEC (RR_direct BC)
  | 0x0C -> INC (R_direct C)
  | 0x0D -> DEC (R_direct C)
  | 0x0E -> LD (R_direct C, Immediate8 (next_byte ()))
  | 0x0F -> RRCA
  | 0x10 -> STOP
  | 0x11 -> LD (RR_direct DE, Immediate16 (next_word ()))
  | 0x12 -> LD (RR_indirect DE, R_direct A)
  | 0x13 -> INC (RR_direct DE)
  | 0x14 -> INC (R_direct D)
  | 0x15 -> DEC (R_direct D)
  | 0x16 -> LD (R_direct D, Immediate8 (next_byte ()))
  | 0x17 -> RLA
  | 0x18 -> JR (No_cond (next_byte ()))
  | 0x19 -> ADD (To_HL (RR_direct DE))
  | 0x1A -> LD (R_direct A, RR_indirect DE)
  | 0x1B -> DEC (RR_direct BC)
  | 0x1C -> INC (R_direct E)
  | 0x1D -> DEC (R_direct E)
  | 0x1E -> LD (R_direct E, Immediate8 (next_byte ()))
  | 0x1F -> RRA
  | 0x20 -> JR (Cond (NZ, next_byte ()))
  | 0x21 -> LD (RR_direct HL, Immediate16 (next_word ()))
  | 0x22 -> LD (HL_inc, R_direct A)
  | 0x23 -> INC (RR_direct HL)
  | 0x24 -> INC (R_direct H)
  | 0x25 -> DEC (R_direct H)
  | 0x26 -> LD (R_direct H, Immediate8 (next_byte ()))
  | 0x27 -> DAA
  | 0x28 -> JR (Cond (Z, next_byte ()))
  | 0x29 -> ADD (To_HL (RR_direct HL))
  | 0x2A -> LD (R_direct A, HL_inc)
  | 0x2B -> DEC (RR_direct HL)
  | 0x2C -> INC (R_direct L)
  | 0x2D -> DEC (R_direct L)
  | 0x2E -> LD (R_direct L, Immediate8 (next_byte ()))
  | 0x2F -> CPL
  | 0x30 -> JR (Cond (NC, next_byte ()))
  | 0x31 -> LD (SP, Immediate16 (next_word ()))
  | 0x32 -> LD (HL_dec, R_direct A)
  | 0x33 -> INC SP
  | 0x34 -> INC HL_indirect
  | 0x35 -> DEC HL_indirect
  | 0x36 -> LD (RR_indirect HL, Immediate8 (next_byte ()))
  | 0x37 -> SCF
  | 0x38 -> JR (Cond (C, next_byte ()))
  | 0x39 -> ADD (To_HL SP)
  | 0x3A -> LD (R_direct A, HL_dec)
  | 0x3B -> DEC SP
  | 0x3C -> INC (R_direct A)
  | 0x3D -> DEC (R_direct A)
  | 0x3E -> LD (R_direct A, Immediate8 (next_byte ()))
  | 0x3F -> CCF
  | 0x40 -> LD (R_direct B, R_direct B)
  | 0x41 -> LD (R_direct B, R_direct C)
  | 0x42 -> LD (R_direct B, R_direct D)
  | 0x43 -> LD (R_direct B, R_direct E)
  | 0x44 -> LD (R_direct B, R_direct H)
  | 0x45 -> LD (R_direct B, R_direct F)
  | 0x46 -> LD (R_direct B, RR_indirect HL)
  | 0x47 -> LD (R_direct B, R_direct A)
  | 0x48 -> LD (R_direct C, R_direct B)
  | 0x49 -> LD (R_direct C, R_direct C)
  | 0x4A -> LD (R_direct C, R_direct D)
  | 0x4B -> LD (R_direct C, R_direct E)
  | 0x4C -> LD (R_direct C, R_direct H)
  | 0x4D -> LD (R_direct C, R_direct L)
  | 0x4E -> LD (R_direct C, RR_indirect HL)
  | 0x4F -> LD (R_direct C, R_direct A)
  | 0x50 -> LD (R_direct D, R_direct B)
  | 0x51 -> LD (R_direct D, R_direct C)
  | 0x52 -> LD (R_direct D, R_direct D)
  | 0x53 -> LD (R_direct D, R_direct E)
  | 0x54 -> LD (R_direct D, R_direct H)
  | 0x55 -> LD (R_direct D, R_direct L)
  | 0x56 -> LD (R_direct D, RR_indirect HL)
  | 0x57 -> LD (R_direct D, R_direct A)
  | 0x58 -> LD (R_direct E, R_direct B)
  | 0x59 -> LD (R_direct E, R_direct C)
  | 0x5A -> LD (R_direct E, R_direct D)
  | 0x5B -> LD (R_direct E, R_direct E)
  | 0x5C -> LD (R_direct E, R_direct H)
  | 0x5D -> LD (R_direct E, R_direct L)
  | 0x5E -> LD (R_direct E, RR_indirect HL)
  | 0x5F -> LD (R_direct E, R_direct A)
  | 0x60 -> LD (R_direct H, R_direct B)
  | 0x61 -> LD (R_direct H, R_direct C)
  | 0x62 -> LD (R_direct H, R_direct D)
  | 0x63 -> LD (R_direct H, R_direct E)
  | 0x64 -> LD (R_direct H, R_direct H)
  | 0x65 -> LD (R_direct H, R_direct L)
  | 0x66 -> LD (R_direct H, RR_indirect HL)
  | 0x67 -> LD (R_direct H, R_direct A)
  | 0x68 -> LD (R_direct L, R_direct B)
  | 0x69 -> LD (R_direct L, R_direct C)
  | 0x6A -> LD (R_direct L, R_direct D)
  | 0x6B -> LD (R_direct L, R_direct E)
  | 0x6C -> LD (R_direct L, R_direct H)
  | 0x6D -> LD (R_direct L, R_direct L)
  | 0x6E -> LD (R_direct L, R_direct E)
  | 0x6F -> LD (R_direct L, R_direct A)
  | 0x70 -> LD (RR_indirect HL, R_direct B)
  | 0x71 -> LD (RR_indirect HL, R_direct C)
  | 0x72 -> LD (RR_indirect HL, R_direct D)
  | 0x73 -> LD (RR_indirect HL, R_direct E)
  | 0x74 -> LD (RR_indirect HL, R_direct H)
  | 0x75 -> LD (RR_indirect HL, R_direct L)
  | 0x76 -> HALT
  | 0x77 -> LD (RR_indirect HL, R_direct A)
  | 0x78 -> LD (R_direct A, R_direct B)
  | 0x79 -> LD (R_direct A, R_direct C)
  | 0x7A -> LD (R_direct A, R_direct D)
  | 0x7B -> LD (R_direct A, R_direct E)
  | 0x7C -> LD (R_direct A, R_direct H)
  | 0x7D -> LD (R_direct A, R_direct L)
  | 0x7E -> LD (R_direct A, RR_indirect HL)
  | 0x7F -> LD (R_direct A, R_direct A)
  | 0x80 -> ADD (To_A (R_direct B))
  | 0x81 -> ADD (To_A (R_direct C))
  | 0x82 -> ADD (To_A (R_direct D))
  | 0x83 -> ADD (To_A (R_direct E))
  | 0x84 -> ADD (To_A (R_direct H))
  | 0x85 -> ADD (To_A (R_direct L))
  | 0x86 -> ADD (To_A (HL_indirect))
  | 0x87 -> ADD (To_A (R_direct A))
  | 0x88 -> ADC (R_direct B)
  | 0x89 -> ADC (R_direct C)
  | 0x8A -> ADC (R_direct D)
  | 0x8B -> ADC (R_direct E)
  | 0x8C -> ADC (R_direct H)
  | 0x8D -> ADC (R_direct L)
  | 0x8E -> ADC (HL_indirect)
  | 0x8F -> ADC (R_direct A)
  | 0x90 -> SUB (R_direct B)
  | 0x91 -> SUB (R_direct C)
  | 0x92 -> SUB (R_direct D)
  | 0x93 -> SUB (R_direct E)
  | 0x94 -> SUB (R_direct H)
  | 0x95 -> SUB (R_direct L)
  | 0x96 -> SUB (HL_indirect)
  | 0x97 -> SUB (R_direct A)
  | 0x98 -> SBC (R_direct B)
  | 0x99 -> SBC (R_direct C)
  | 0x9A -> SBC (R_direct D)
  | 0x9B -> SBC (R_direct E)
  | 0x9C -> SBC (R_direct H)
  | 0x9D -> SBC (R_direct L)
  | 0x9E -> SBC (HL_indirect)
  | 0x9F -> SBC (R_direct A)
  | 0xA0 -> AND (R_direct B)
  | 0xA1 -> AND (R_direct C)
  | 0xA2 -> AND (R_direct D)
  | 0xA3 -> AND (R_direct E)
  | 0xA4 -> AND (R_direct H)
  | 0xA5 -> AND (R_direct L)
  | 0xA6 -> AND (HL_indirect)
  | 0xA7 -> AND (R_direct A)
  | 0xA8 -> XOR (R_direct B)
  | 0xA9 -> XOR (R_direct C)
  | 0xAA -> XOR (R_direct D)
  | 0xAB -> XOR (R_direct E)
  | 0xAC -> XOR (R_direct H)
  | 0xAD -> XOR (R_direct L)
  | 0xAE -> XOR (HL_indirect)
  | 0xAF -> XOR (R_direct A)
  | 0xB0 -> OR (R_direct B)
  | 0xB1 -> OR (R_direct C)
  | 0xB2 -> OR (R_direct D)
  | 0xB3 -> OR (R_direct E)
  | 0xB4 -> OR (R_direct H)
  | 0xB5 -> OR (R_direct L)
  | 0xB6 -> OR (HL_indirect)
  | 0xB7 -> OR (R_direct A)
  | 0xB8 -> CP (R_direct B)
  | 0xB9 -> CP (R_direct C)
  | 0xBA -> CP (R_direct D)
  | 0xBB -> CP (R_direct E)
  | 0xBC -> CP (R_direct H)
  | 0xBD -> CP (R_direct L)
  | 0xBE -> CP (HL_indirect)
  | 0xBF -> CP (R_direct A)
  | 0xC0 -> RET (Cond NZ)
  | 0xC1 -> POP (RR_direct BC)
  | 0xC2 -> JP (Cond (NZ, next_word ()))
  | 0xC3 -> JP (No_cond (next_word ()))
  | 0xC4 -> CALL (Cond (NZ, next_word ()))
  | 0xC5 -> PUSH (RR_direct BC)
  | 0xC6 -> ADD (To_A (Immediate (next_byte ())))
  | 0xC7 -> RST (Uint16.zero)
  | 0xC8 -> RET (Cond Z)
  | 0xC9 -> RET No_cond
  | 0xCA -> JP (Cond (Z, next_word ()))
  | 0xCC -> CALL (Cond (Z, next_word ()))
  | 0xCD -> CALL (No_cond (next_word ()))
  | 0xCE -> ADC (Immediate (next_byte ()))
  | 0xCF -> RST Constants.u16_8
  | 0xD0 -> RET (Cond NC)
  | 0xD1 -> POP (RR_direct DE)
  | 0xD2 -> JP (Cond (NC, next_word ()))
  | 0xD3 -> NOP
  | 0xD4 -> CALL (Cond (NC, next_word ()))
  | 0xD5 -> PUSH (RR_direct DE)
  | 0xD6 -> SUB (Immediate (next_byte ()))
  | 0xD7 -> RST Constants.u16_10
  | 0xD8 -> RET (Cond C)
  | 0xD9 -> RETI
  | 0xDA -> RET (Cond NZ)
  | 0xDB -> NOP
  | 0xDC -> CALL (Cond (C, next_word ()))
  | 0xDD -> NOP
  | 0xDE -> SBC (Immediate (next_byte ()))
  | 0xDF -> RST Constants.u16_18
  | 0xE0 -> LD (FF00_offset (next_byte ()), R_direct A)
  | 0xE1 -> POP (RR_direct HL)
  | 0xE2 -> LD (FF00_C, R_direct A)
  | 0xE3 -> NOP
  | 0xE4 -> NOP
  | 0xE5 -> PUSH (RR_direct HL)
  | 0xE6 -> AND (Immediate (next_byte ()))
  | 0xE7 -> RST Constants.u16_20
  | 0xE8 -> ADD (To_SP (next_byte ()))
  | 0xE9 -> JP (HL_indirect)
  | 0xEA -> LD (Immediate16 (next_word ()), R_direct A)
  | 0xEB -> NOP
  | 0xEC -> NOP
  | 0xED -> NOP
  | 0xEE -> XOR (Immediate (next_byte ()))
  | 0xEF -> RST Constants.u16_28
  | 0xF0 -> LD (R_direct A, FF00_offset (next_byte ()))
  | 0xF1 -> POP (RR_direct AF)
  | 0xF2 -> LD (R_direct A, FF00_C)
  | 0xF3 -> DI
  | 0xF4 -> NOP
  | 0xF5 -> PUSH (RR_direct AF)
  | 0xF6 -> OR (Immediate (next_byte ()))
  | 0xF7 -> RST Constants.u16_30
  | 0xF8 -> LD (RR_direct HL, SP)
  | 0xF9 -> LD (SP, RR_direct HL)
  | 0xFA -> LD (R_direct A, Immediate16 (next_word ()))
  | 0xFB -> EI
  | 0xFC -> NOP
  | 0xFD -> NOP
  | 0xFE -> CP (Immediate (next_byte ()))
  | 0xFF -> RST Constants.u16_38
  | 0xCB -> (
      let op = next_byte () |> Uint8.to_int in
      match op with
      | 0x00 -> RLC (R_direct B)
      | 0x01 -> RLC (R_direct C)
      | 0x02 -> RLC (R_direct D)
      | 0x03 -> RLC (R_direct E)
      | 0x04 -> RLC (R_direct H)
      | 0x05 -> RLC (R_direct L)
      | 0x06 -> RLC (HL_indirect)
      | 0x07 -> RRC (R_direct A)
      | 0x08 -> RRC (R_direct B)
      | 0x09 -> RRC (R_direct C)
      | 0x0A -> RRC (R_direct D)
      | 0x0B -> RRC (R_direct E)
      | 0x0C -> RRC (R_direct H)
      | 0x0D -> RRC (R_direct L)
      | 0x0E -> RRC (HL_indirect)
      | 0x0F -> RRC (R_direct A)
      | 0x10 -> RL (R_direct B)
      | 0x11 -> RL (R_direct C)
      | 0x12 -> RL (R_direct D)
      | 0x13 -> RL (R_direct E)
      | 0x14 -> RL (R_direct H)
      | 0x15 -> RL (R_direct L)
      | 0x16 -> RL (HL_indirect)
      | 0x17 -> RR (R_direct A)
      | 0x18 -> RR (R_direct B)
      | 0x19 -> RR (R_direct C)
      | 0x1A -> RR (R_direct D)
      | 0x1B -> RR (R_direct E)
      | 0x1C -> RR (R_direct H)
      | 0x1D -> RR (R_direct L)
      | 0x1E -> RR (HL_indirect)
      | 0x1F -> RR (R_direct A)
      | 0x20 -> SLA (R_direct B)
      | 0x21 -> SLA (R_direct C)
      | 0x22 -> SLA (R_direct D)
      | 0x23 -> SLA (R_direct E)
      | 0x24 -> SLA (R_direct H)
      | 0x25 -> SLA (R_direct L)
      | 0x26 -> SLA (HL_indirect)
      | 0x27 -> SRA (R_direct A)
      | 0x28 -> SRA (R_direct B)
      | 0x29 -> SRA (R_direct C)
      | 0x2A -> SRA (R_direct D)
      | 0x2B -> SRA (R_direct E)
      | 0x2C -> SRA (R_direct H)
      | 0x2D -> SRA (R_direct L)
      | 0x2E -> SRA (HL_indirect)
      | 0x2F -> SRA (R_direct A)
      | 0x30 -> SWAP (R_direct B)
      | 0x31 -> SWAP (R_direct C)
      | 0x32 -> SWAP (R_direct D)
      | 0x33 -> SWAP (R_direct E)
      | 0x34 -> SWAP (R_direct H)
      | 0x35 -> SWAP (R_direct L)
      | 0x36 -> SWAP (HL_indirect)
      | 0x37 -> SRL (R_direct A)
      | 0x38 -> SRL (R_direct B)
      | 0x39 -> SRL (R_direct C)
      | 0x3A -> SRL (R_direct D)
      | 0x3B -> SRL (R_direct E)
      | 0x3C -> SRL (R_direct H)
      | 0x3D -> SRL (R_direct L)
      | 0x3E -> SRL (HL_indirect)
      | 0x3F -> SRL (R_direct A)
      | 0x40 -> BIT (Uint8.zero, R_direct B)
      | 0x41 -> BIT (Uint8.zero, R_direct C)
      | 0x42 -> BIT (Uint8.zero, R_direct D)
      | 0x43 -> BIT (Uint8.zero, R_direct E)
      | 0x44 -> BIT (Uint8.zero, R_direct H)
      | 0x45 -> BIT (Uint8.zero, R_direct L)
      | 0x46 -> BIT (Uint8.zero, HL_indirect)
      | 0x47 -> BIT (Uint8.one, R_direct A)
      | 0x48 -> BIT (Uint8.one, R_direct B)
      | 0x49 -> BIT (Uint8.one, R_direct C)
      | 0x4A -> BIT (Uint8.one, R_direct D)
      | 0x4B -> BIT (Uint8.one, R_direct E)
      | 0x4C -> BIT (Uint8.one, R_direct H)
      | 0x4D -> BIT (Uint8.one, R_direct L)
      | 0x4E -> BIT (Uint8.one, HL_indirect)
      | 0x4F -> BIT (Uint8.one, R_direct A)
      | 0x50 -> BIT (Constants.u8_2, R_direct B)
      | 0x51 -> BIT (Constants.u8_2, R_direct C)
      | 0x52 -> BIT (Constants.u8_2, R_direct D)
      | 0x53 -> BIT (Constants.u8_2, R_direct E)
      | 0x54 -> BIT (Constants.u8_2, R_direct H)
      | 0x55 -> BIT (Constants.u8_2, R_direct L)
      | 0x56 -> BIT (Constants.u8_2, HL_indirect)
      | 0x57 -> BIT (Constants.u8_3,  R_direct A)
      | 0x58 -> BIT (Constants.u8_3,  R_direct B)
      | 0x59 -> BIT (Constants.u8_3,  R_direct C)
      | 0x5A -> BIT (Constants.u8_3,  R_direct D)
      | 0x5B -> BIT (Constants.u8_3,  R_direct E)
      | 0x5C -> BIT (Constants.u8_3,  R_direct H)
      | 0x5D -> BIT (Constants.u8_3,  R_direct L)
      | 0x5E -> BIT (Constants.u8_3,  HL_indirect)
      | 0x5F -> BIT (Constants.u8_3,  R_direct A)
      | 0x60 -> BIT (Constants.u8_4, R_direct B)
      | 0x61 -> BIT (Constants.u8_4, R_direct C)
      | 0x62 -> BIT (Constants.u8_4, R_direct D)
      | 0x63 -> BIT (Constants.u8_4, R_direct E)
      | 0x64 -> BIT (Constants.u8_4, R_direct H)
      | 0x65 -> BIT (Constants.u8_4, R_direct L)
      | 0x66 -> BIT (Constants.u8_4, HL_indirect)
      | 0x67 -> BIT (Constants.u8_5,  R_direct A)
      | 0x68 -> BIT (Constants.u8_5,  R_direct B)
      | 0x69 -> BIT (Constants.u8_5,  R_direct C)
      | 0x6A -> BIT (Constants.u8_5,  R_direct D)
      | 0x6B -> BIT (Constants.u8_5,  R_direct E)
      | 0x6C -> BIT (Constants.u8_5,  R_direct H)
      | 0x6D -> BIT (Constants.u8_5,  R_direct L)
      | 0x6E -> BIT (Constants.u8_5,  HL_indirect)
      | 0x6F -> BIT (Constants.u8_5,  R_direct A)
      | 0x70 -> BIT (Constants.u8_6, R_direct B)
      | 0x71 -> BIT (Constants.u8_6, R_direct C)
      | 0x72 -> BIT (Constants.u8_6, R_direct D)
      | 0x73 -> BIT (Constants.u8_6, R_direct E)
      | 0x74 -> BIT (Constants.u8_6, R_direct H)
      | 0x75 -> BIT (Constants.u8_6, R_direct L)
      | 0x76 -> BIT (Constants.u8_6, HL_indirect)
      | 0x77 -> BIT (Constants.u8_7,  R_direct A)
      | 0x78 -> BIT (Constants.u8_7,  R_direct B)
      | 0x79 -> BIT (Constants.u8_7,  R_direct C)
      | 0x7A -> BIT (Constants.u8_7,  R_direct D)
      | 0x7B -> BIT (Constants.u8_7,  R_direct E)
      | 0x7C -> BIT (Constants.u8_7,  R_direct H)
      | 0x7D -> BIT (Constants.u8_7,  R_direct L)
      | 0x7E -> BIT (Constants.u8_7,  HL_indirect)
      | 0x7F -> BIT (Constants.u8_7,  R_direct A)
      | 0x80 -> RES (Uint8.zero, R_direct B)
      | 0x81 -> RES (Uint8.zero, R_direct C)
      | 0x82 -> RES (Uint8.zero, R_direct D)
      | 0x83 -> RES (Uint8.zero, R_direct E)
      | 0x84 -> RES (Uint8.zero, R_direct H)
      | 0x85 -> RES (Uint8.zero, R_direct L)
      | 0x86 -> RES (Uint8.zero, HL_indirect)
      | 0x87 -> RES (Uint8.one, R_direct A)
      | 0x88 -> RES (Uint8.one, R_direct B)
      | 0x89 -> RES (Uint8.one, R_direct C)
      | 0x8A -> RES (Uint8.one, R_direct D)
      | 0x8B -> RES (Uint8.one, R_direct E)
      | 0x8C -> RES (Uint8.one, R_direct H)
      | 0x8D -> RES (Uint8.one, R_direct L)
      | 0x8E -> RES (Uint8.one, HL_indirect)
      | 0x8F -> RES (Uint8.one, R_direct A)
      | 0x90 -> RES (Constants.u8_2, R_direct B)
      | 0x91 -> RES (Constants.u8_2, R_direct C)
      | 0x92 -> RES (Constants.u8_2, R_direct D)
      | 0x93 -> RES (Constants.u8_2, R_direct E)
      | 0x94 -> RES (Constants.u8_2, R_direct H)
      | 0x95 -> RES (Constants.u8_2, R_direct L)
      | 0x96 -> RES (Constants.u8_2, HL_indirect)
      | 0x97 -> RES (Constants.u8_3,  R_direct A)
      | 0x98 -> RES (Constants.u8_3,  R_direct B)
      | 0x99 -> RES (Constants.u8_3,  R_direct C)
      | 0x9A -> RES (Constants.u8_3,  R_direct D)
      | 0x9B -> RES (Constants.u8_3,  R_direct E)
      | 0x9C -> RES (Constants.u8_3,  R_direct H)
      | 0x9D -> RES (Constants.u8_3,  R_direct L)
      | 0x9E -> RES (Constants.u8_3,  HL_indirect)
      | 0x9F -> RES (Constants.u8_3,  R_direct A)
      | 0xA0 -> RES (Constants.u8_4, R_direct B)
      | 0xA1 -> RES (Constants.u8_4, R_direct C)
      | 0xA2 -> RES (Constants.u8_4, R_direct D)
      | 0xA3 -> RES (Constants.u8_4, R_direct E)
      | 0xA4 -> RES (Constants.u8_4, R_direct H)
      | 0xA5 -> RES (Constants.u8_4, R_direct L)
      | 0xA6 -> RES (Constants.u8_4, HL_indirect)
      | 0xA7 -> RES (Constants.u8_5,  R_direct A)
      | 0xA8 -> RES (Constants.u8_5,  R_direct B)
      | 0xA9 -> RES (Constants.u8_5,  R_direct C)
      | 0xAA -> RES (Constants.u8_5,  R_direct D)
      | 0xAB -> RES (Constants.u8_5,  R_direct E)
      | 0xAC -> RES (Constants.u8_5,  R_direct H)
      | 0xAD -> RES (Constants.u8_5,  R_direct L)
      | 0xAE -> RES (Constants.u8_5,  HL_indirect)
      | 0xAF -> RES (Constants.u8_5,  R_direct A)
      | 0xB0 -> RES (Constants.u8_6, R_direct B)
      | 0xB1 -> RES (Constants.u8_6, R_direct C)
      | 0xB2 -> RES (Constants.u8_6, R_direct D)
      | 0xB3 -> RES (Constants.u8_6, R_direct E)
      | 0xB4 -> RES (Constants.u8_6, R_direct H)
      | 0xB5 -> RES (Constants.u8_6, R_direct L)
      | 0xB6 -> RES (Constants.u8_6, HL_indirect)
      | 0xB7 -> RES (Constants.u8_7,  R_direct A)
      | 0xB8 -> RES (Constants.u8_7,  R_direct B)
      | 0xB9 -> RES (Constants.u8_7,  R_direct C)
      | 0xBA -> RES (Constants.u8_7,  R_direct D)
      | 0xBB -> RES (Constants.u8_7,  R_direct E)
      | 0xBC -> RES (Constants.u8_7,  R_direct H)
      | 0xBD -> RES (Constants.u8_7,  R_direct L)
      | 0xBE -> RES (Constants.u8_7,  HL_indirect)
      | 0xBF -> RES (Constants.u8_7,  R_direct A)
      | 0xC0 -> SET (Uint8.zero, R_direct B)
      | 0xC1 -> SET (Uint8.zero, R_direct C)
      | 0xC2 -> SET (Uint8.zero, R_direct D)
      | 0xC3 -> SET (Uint8.zero, R_direct E)
      | 0xC4 -> SET (Uint8.zero, R_direct H)
      | 0xC5 -> SET (Uint8.zero, R_direct L)
      | 0xC6 -> SET (Uint8.zero, HL_indirect)
      | 0xC7 -> SET (Uint8.one, R_direct A)
      | 0xC8 -> SET (Uint8.one, R_direct B)
      | 0xC9 -> SET (Uint8.one, R_direct C)
      | 0xCA -> SET (Uint8.one, R_direct D)
      | 0xCB -> SET (Uint8.one, R_direct E)
      | 0xCC -> SET (Uint8.one, R_direct H)
      | 0xCD -> SET (Uint8.one, R_direct L)
      | 0xCE -> SET (Uint8.one, HL_indirect)
      | 0xCF -> SET (Uint8.one, R_direct A)
      | 0xD0 -> SET (Constants.u8_2, R_direct B)
      | 0xD1 -> SET (Constants.u8_2, R_direct C)
      | 0xD2 -> SET (Constants.u8_2, R_direct D)
      | 0xD3 -> SET (Constants.u8_2, R_direct E)
      | 0xD4 -> SET (Constants.u8_2, R_direct H)
      | 0xD5 -> SET (Constants.u8_2, R_direct L)
      | 0xD6 -> SET (Constants.u8_2, HL_indirect)
      | 0xD7 -> SET (Constants.u8_3,  R_direct A)
      | 0xD8 -> SET (Constants.u8_3,  R_direct B)
      | 0xD9 -> SET (Constants.u8_3,  R_direct C)
      | 0xDA -> SET (Constants.u8_3,  R_direct D)
      | 0xDB -> SET (Constants.u8_3,  R_direct E)
      | 0xDC -> SET (Constants.u8_3,  R_direct H)
      | 0xDD -> SET (Constants.u8_3,  R_direct L)
      | 0xDE -> SET (Constants.u8_3,  HL_indirect)
      | 0xDF -> SET (Constants.u8_3,  R_direct A)
      | 0xE0 -> SET (Constants.u8_4, R_direct B)
      | 0xE1 -> SET (Constants.u8_4, R_direct C)
      | 0xE2 -> SET (Constants.u8_4, R_direct D)
      | 0xE3 -> SET (Constants.u8_4, R_direct E)
      | 0xE4 -> SET (Constants.u8_4, R_direct H)
      | 0xE5 -> SET (Constants.u8_4, R_direct L)
      | 0xE6 -> SET (Constants.u8_4, HL_indirect)
      | 0xE7 -> SET (Constants.u8_5,  R_direct A)
      | 0xE8 -> SET (Constants.u8_5,  R_direct B)
      | 0xE9 -> SET (Constants.u8_5,  R_direct C)
      | 0xEA -> SET (Constants.u8_5,  R_direct D)
      | 0xEB -> SET (Constants.u8_5,  R_direct E)
      | 0xEC -> SET (Constants.u8_5,  R_direct H)
      | 0xED -> SET (Constants.u8_5,  R_direct L)
      | 0xEE -> SET (Constants.u8_5,  HL_indirect)
      | 0xEF -> SET (Constants.u8_5,  R_direct A)
      | 0xF0 -> SET (Constants.u8_6, R_direct B)
      | 0xF1 -> SET (Constants.u8_6, R_direct C)
      | 0xF2 -> SET (Constants.u8_6, R_direct D)
      | 0xF3 -> SET (Constants.u8_6, R_direct E)
      | 0xF4 -> SET (Constants.u8_6, R_direct H)
      | 0xF5 -> SET (Constants.u8_6, R_direct L)
      | 0xF6 -> SET (Constants.u8_6, HL_indirect)
      | 0xF7 -> SET (Constants.u8_7,  R_direct A)
      | 0xF8 -> SET (Constants.u8_7,  R_direct B)
      | 0xF9 -> SET (Constants.u8_7,  R_direct C)
      | 0xFA -> SET (Constants.u8_7,  R_direct D)
      | 0xFB -> SET (Constants.u8_7,  R_direct E)
      | 0xFC -> SET (Constants.u8_7,  R_direct H)
      | 0xFD -> SET (Constants.u8_7,  R_direct L)
      | 0xFE -> SET (Constants.u8_7,  HL_indirect)
      | 0xFF -> SET (Constants.u8_7,  R_direct A)
      | _ -> failwith (Printf.sprintf "Unrecognized opcode after 0xCB: 0x%02x" op)
    )
  | _ -> failwith (Printf.sprintf "Unrecognized opcode: 0x%02x" op)
